<?php

namespace folosuru\item_storage;

use pocketmine\scheduler\AsyncTask;

class DataLoadTask extends AsyncTask {

	private string $path;

	public function __construct(string $path){
		$this->path = $path;
	}

	public function onRun(): void{
		$result = [];
		foreach (glob($this->path."*.json") as $item) {
			$name = str_replace('.json','',str_replace($this->path,'', $item));
			$result[$name] = file_get_contents($item);
		}
		$this->setResult($result);
	}

	public function onCompletion(): void{
		parent::onCompletion(); // TODO: Change the autogenerated stub
		$result=[];
		foreach ($this->getResult() as $key => $item){
			$result[$key] = new ItemStorage();
			$result[$key]->setAllItem(json_decode($item,true));
		}
		Main::getInstance()->setStorage($result);
	}

}